# Site Settings
title: Speechless
tagline: Speechless
email: 2655342843@qq.com
description: >
  The  site for Speechless, made for Jekyll and GitHub pages websites.Overseas live broadcast in small languages brings goods
baseurl: "/mere-blog-theme"
url: "https://www.csrhymes.com"
permalink: pretty

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: /img/home.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

collections:
  authors:
    output: true
